name: Wheels

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

# Reminder
# - name: Extract Branch Name
#   run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
# https://dev.to/tomassirio/if-statements-on-github-actions-545d

jobs:
  wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed by setuptools_scm

      - run: python -m pip install build
      - run: python -m build
      - run: python -m pip install $(echo dist/*.whl)'[test]'
      - run: python -m pytest

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.*

  upload:
    needs: wheel
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.ref, '/tags/')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{secrets.PYPI_API_TOKEN}}
