name: Test

on:
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.python }} ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: '3.8'
            arch: 'x64'
            os: 'windows-latest'
          - python: '3.10'
            arch: 'x64'
            os: 'macos-latest'
          - python: '3.11'
            arch: 'x64'
            os: 'ubuntu-latest'
        # Broken for some reason not related to us
        # - python: 'pypy-3.8'
        #   arch: 'x64'
        #   os: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/cache@v3
      with:
        path: ~/.cachier
        key: ${{ runner.os }}-cachier
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.arch }}
    - run: python -m pip install --progress-bar=off --prefer-binary -e .[test]
    - run: python -m pytest
